### ISSUE TITLE
Missing generic SLURM template

### ISSUE THREAD

**Issue by Bai-Chiang** [simonsobs/mbatch#23]
When running `example/example.yml` on my local machine with SLURM installed, it failed to find `mbatch/data/sites/generic.yml`.

Error message:
```
slurm 22.05.10
/home/bai-chiang/git/mbatch/mbatch/mbatch.py:148: UserWarning: No site specified through --site and did not automatically detect any sites. Using generic SLURM template.
  warnings.warn('No site specified through --site and did not automatically detect any sites. Using generic SLURM template.')
Traceback (most recent call last):
  File "/home/bai-chiang/micromamba/envs/bbmaster/bin/mbatch", line 33, in <module>
    sys.exit(load_entry_point('mbatch', 'console_scripts', 'mbatch')())
  File "/home/bai-chiang/git/mbatch/mbatch/mbatch.py", line 630, in main
    sbatch_config = load_template(site)
  File "/home/bai-chiang/git/mbatch/mbatch/mbatch.py", line 169, in load_template
    with open(template_path, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bai-chiang/git/mbatch/mbatch/data/sites/generic.yml'
```

- If I uninstall `slurm` package it would run as `README.md` showed. Of course it won't detect SLURM.
- If `slurm` is installed, but SLURM service are not running (`slurmctld.service` and `slurmd.service` are stopped) , it still failed. Same error message as showed. Maybe could have a better way to determine SLURM is running or not. I may think about a better way to handle this function.
https://github.com/simonsobs/mbatch/blob/70629725abef8c85fc613bbcccd878031717b17c/mbatch/mbatch.py#L68

**Comment by msyriac** [comment]
Fixed with #24, thank you @Bai-Chiang
